# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shrinkage <- function(a, kappa) {
    .Call(`_CNIF2_shrinkage`, a, kappa)
}

covsel <- function(d, max_iter = 1000L, alpha = 1.2, lambda = 0.0001, rho = 0.5) {
    .Call(`_CNIF2_covsel`, d, max_iter, alpha, lambda, rho)
}

lasso <- function(A, b, max_iter = 1000L, alpha = 1.2, lambda = 0.1, rho = 1) {
    .Call(`_CNIF2_lasso`, A, b, max_iter, alpha, lambda, rho)
}

ca_mean <- function(x) {
    .Call(`_CNIF2_ca_mean`, x)
}

ca_var <- function(x) {
    .Call(`_CNIF2_ca_var`, x)
}

center_scale <- function(x) {
    .Call(`_CNIF2_center_scale`, x)
}

initial_sem_nofix <- function(data, variable, rho = 1.0, lambda = 0.1, prec = 1e-5, max_iter = 1000L) {
    .Call(`_CNIF2_initial_sem_nofix`, data, variable, rho, lambda, prec, max_iter)
}

initial_sem <- function(data, fixed, variable, rho = 1.0, lambda = 0.1, prec = 1e-5, max_iter = 1000L) {
    .Call(`_CNIF2_initial_sem`, data, fixed, variable, rho, lambda, prec, max_iter)
}

score_function_regression_with_fix <- function(node, parents, fixed, data) {
    .Call(`_CNIF2_score_function_regression_with_fix`, node, parents, fixed, data)
}

score_function_regression <- function(node, parents, data) {
    .Call(`_CNIF2_score_function_regression`, node, parents, data)
}

get_cycles <- function(adjMat) {
    .Call(`_CNIF2_get_cycles`, adjMat)
}

