# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shrinkage <- function(a, kappa) {
    .Call('CNIF_shrinkage', PACKAGE = 'CNIF', a, kappa)
}

covsel <- function(d, max_iter = 1000L, alpha = 1.2, lambda = 0.0001, rho = 0.5) {
    .Call('CNIF_covsel', PACKAGE = 'CNIF', d, max_iter, alpha, lambda, rho)
}

lasso <- function(A, b, max_iter = 1000L, alpha = 1.2, lambda = 0.1, rho = 1) {
    .Call('CNIF_lasso', PACKAGE = 'CNIF', A, b, max_iter, alpha, lambda, rho)
}

ca_mean <- function(x) {
    .Call('CNIF_ca_mean', PACKAGE = 'CNIF', x)
}

ca_var <- function(x) {
    .Call('CNIF_ca_var', PACKAGE = 'CNIF', x)
}

center_scale <- function(x) {
    .Call('CNIF_center_scale', PACKAGE = 'CNIF', x)
}

initial_sem_nofix <- function(data, variable, rho = 1.0, lambda = 0.1, prec = 1e-5, max_iter = 1000L) {
    .Call('CNIF_initial_sem_nofix', PACKAGE = 'CNIF', data, variable, rho, lambda, prec, max_iter)
}

initial_sem <- function(data, fixed, variable, rho = 1.0, lambda = 0.1, prec = 1e-5, max_iter = 1000L) {
    .Call('CNIF_initial_sem', PACKAGE = 'CNIF', data, fixed, variable, rho, lambda, prec, max_iter)
}

score_function_regression_with_fix <- function(node, parents, fixed, data) {
    .Call('CNIF_score_function_regression_with_fix', PACKAGE = 'CNIF', node, parents, fixed, data)
}

score_function_regression <- function(node, parents, data) {
    .Call('CNIF_score_function_regression', PACKAGE = 'CNIF', node, parents, data)
}

get_cycles <- function(adjMat) {
    .Call('CNIF_get_cycles', PACKAGE = 'CNIF', adjMat)
}

